#!/usr/bin/env bash
set -euo pipefail

# First auto-research improvement wave after ACDL completion.
# All training/eval jobs are single-GPU by default. Preserve failed candidates.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
PROJECT_ROOT="${PROJECT_ROOT:-$REPO_ROOT}"
DATA_DIR="${DATA_DIR:-data/real_subset_clean_260708b}"
STAMP="${STAMP:-260709next}"
GPU="${GPU:-1}"
CPU="${CPU:-8}"
MEMORY="${MEMORY:-120G}"

submit_e3() {
  local name="$1"
  shift
  echo "Submitting E3 candidate: ${name}"
  env \
    JOB_NAME="$name" \
    OUT="outputs/${name}" \
    DATA_DIR="$DATA_DIR" \
    GPU="$GPU" CPU="$CPU" MEMORY="$MEMORY" \
    ABLATION_STEPS=0 CAPACITY_ABLATION_STEPS=0 EXPERT_ABLATION_STEPS=0 \
    POSTPROCESS_REQUIRED_RUNS=0 \
    TEXT_EVAL_BLOCKS=160 RETRIEVAL_EVAL_SAMPLES=250 CONDITIONAL_EVAL_SAMPLES=250 \
    IMAGE_EVAL_SAMPLES=250 SPEECH_EVAL_SAMPLES=250 \
    TRAIN_BATCH_SIZE=4 EVAL_BATCH_SIZE=8 TRAIN_LM_HEAD=1 TRAIN_EXPERTS=0 \
    IMAGE_PREFIX_TOKENS=50 AUDIO_PREFIX_TOKENS=64 ENCODER_FEATURE_TOKENS=100 \
    REAL_MAX_SOURCE_AUDIO_SECONDS=6 REAL_MAX_TRANSCRIPT_WORDS=18 \
    "$@" \
    bash scripts/submit_e3_candidate_runai.sh
}

submit_distill() {
  local name="$1"
  shift
  echo "Submitting Top-2 distillation candidate: ${name}"
  env \
    JOB_NAME="$name" \
    OUT="${PROJECT_ROOT}/outputs/${name}" \
    DATA_DIR="${PROJECT_ROOT}/${DATA_DIR}" \
    GPU="$GPU" CPU="$CPU" MEMORY="$MEMORY" \
    "$@" \
    bash scripts/submit_top2_distill_runai.sh
}

# Multimodal candidates: target 50/250-way and hard-negative weaknesses.
submit_e3 "sparse-moe-mm-rank49-fullbank-cap7-${STAMP}" \
  FINAL_STEPS=6000 \
  CAPACITY_FACTOR=7.0 AUX_COEF=0.02 \
  MODALITY_CYCLE=text,image,image,speech,speech \
  LEARNING_RATE=0.0005 LM_HEAD_LEARNING_RATE=0.00001 RETRIEVAL_HEAD_LEARNING_RATE=0.0015 \
  CONTRASTIVE_COEF=0.15 IMAGE_CONTRASTIVE_COEF=0.4 SPEECH_CONTRASTIVE_COEF=0.6 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=49 CONDITIONAL_RANKING_NEGATIVE_MODE=random \
  IMAGE_CONDITIONAL_RANKING_COEF=1.0 SPEECH_CONDITIONAL_RANKING_COEF=2.5 \
  CONDITIONAL_RANKING_TEMPERATURE=0.7

submit_e3 "sparse-moe-mm-prefix75-balanced-cap8-${STAMP}" \
  FINAL_STEPS=6000 \
  CAPACITY_FACTOR=8.0 AUX_COEF=0.015 \
  MODALITY_CYCLE=text,image,image,speech,speech,speech \
  LEARNING_RATE=0.00045 LM_HEAD_LEARNING_RATE=0.00001 RETRIEVAL_HEAD_LEARNING_RATE=0.001 \
  IMAGE_PREFIX_TOKENS=75 AUDIO_PREFIX_TOKENS=64 ENCODER_FEATURE_TOKENS=100 \
  CONTRASTIVE_COEF=0.1 IMAGE_CONTRASTIVE_COEF=0.25 SPEECH_CONTRASTIVE_COEF=0.5 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=19 CONDITIONAL_RANKING_NEGATIVE_MODE=random \
  IMAGE_CONDITIONAL_RANKING_COEF=2.0 SPEECH_CONDITIONAL_RANKING_COEF=2.0 \
  CONDITIONAL_RANKING_TEMPERATURE=0.7

submit_e3 "sparse-moe-mm-whisper-space-cap6-${STAMP}" \
  FINAL_STEPS=5000 \
  CAPACITY_FACTOR=6.0 AUX_COEF=0.01 SPEECH_TARGET_SPACE=whisper_decoder_text \
  MODALITY_CYCLE=text,image,speech,speech,speech \
  LEARNING_RATE=0.0004 LM_HEAD_LEARNING_RATE=0.00001 RETRIEVAL_HEAD_LEARNING_RATE=0.002 \
  ALIGNMENT_PRETRAIN_STEPS=800 \
  CONTRASTIVE_COEF=0.1 IMAGE_CONTRASTIVE_COEF=0.25 SPEECH_CONTRASTIVE_COEF=0.8 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  SPEECH_CENTER_POSITIVE_WEIGHT=1.0 SPEECH_RAW_POSITIVE_WEIGHT=2.0 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVE_MODE=random \
  IMAGE_CONDITIONAL_RANKING_COEF=1.0 SPEECH_CONDITIONAL_RANKING_COEF=2.5

# Routing candidates: preserve selected recipe while reducing overflow/inactive.
submit_e3 "sparse-moe-route-z3e5-cap7-img15-${STAMP}" \
  FINAL_STEPS=5000 \
  CAPACITY_FACTOR=7.0 AUX_COEF=0.015 ROUTER_Z_LOSS_COEF=0.00003 \
  MODALITY_CYCLE=text,image,speech,speech,speech \
  CONTRASTIVE_COEF=0.2 IMAGE_CONTRASTIVE_COEF=0.5 SPEECH_CONTRASTIVE_COEF=0.5 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  IMAGE_CONDITIONAL_RANKING_COEF=1.5 SPEECH_CONDITIONAL_RANKING_COEF=2.0 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVE_MODE=random

submit_e3 "sparse-moe-route-drop02-cap7-img15-${STAMP}" \
  FINAL_STEPS=5000 \
  CAPACITY_FACTOR=7.0 AUX_COEF=0.015 EXPERT_DROPOUT_PROB=0.02 \
  MODALITY_CYCLE=text,image,speech,speech,speech \
  CONTRASTIVE_COEF=0.2 IMAGE_CONTRASTIVE_COEF=0.5 SPEECH_CONTRASTIVE_COEF=0.5 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  IMAGE_CONDITIONAL_RANKING_COEF=1.5 SPEECH_CONDITIONAL_RANKING_COEF=2.0 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVE_MODE=random

submit_e3 "sparse-moe-route-dynbias-cap7-img15-${STAMP}" \
  FINAL_STEPS=5000 \
  CAPACITY_FACTOR=7.0 AUX_COEF=0.015 DYNAMIC_EXPERT_BIAS_LR=0.001 \
  DYNAMIC_EXPERT_BIAS_UPDATE_INTERVAL=1 DYNAMIC_EXPERT_BIAS_WARMUP_STEPS=50 DYNAMIC_EXPERT_BIAS_MAX_ABS=1.5 \
  MODALITY_CYCLE=text,image,speech,speech,speech \
  CONTRASTIVE_COEF=0.2 IMAGE_CONTRASTIVE_COEF=0.5 SPEECH_CONTRASTIVE_COEF=0.5 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  IMAGE_CONDITIONAL_RANKING_COEF=1.5 SPEECH_CONDITIONAL_RANKING_COEF=2.0 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVE_MODE=random

submit_e3 "sparse-moe-mm-hardtext-rank19-cap7-${STAMP}" \
  FINAL_STEPS=5000 \
  CAPACITY_FACTOR=7.0 AUX_COEF=0.015 \
  MODALITY_CYCLE=text,image,image,speech,speech \
  LEARNING_RATE=0.00045 LM_HEAD_LEARNING_RATE=0.00001 RETRIEVAL_HEAD_LEARNING_RATE=0.001 \
  CONTRASTIVE_COEF=0.15 IMAGE_CONTRASTIVE_COEF=0.4 SPEECH_CONTRASTIVE_COEF=0.6 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  IMAGE_CONDITIONAL_RANKING_COEF=1.5 SPEECH_CONDITIONAL_RANKING_COEF=2.0 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=19 CONDITIONAL_RANKING_NEGATIVE_MODE=hard_text \
  CONDITIONAL_RANKING_HARD_POOL_SIZE=1024 CONDITIONAL_RANKING_TEMPERATURE=0.7

# Router-stability controls: isolate whether gate drift hurts routing/conditional matching.
submit_e3 "sparse-moe-mm-routerlite-cap7-img15-${STAMP}" \
  FINAL_STEPS=5000 \
  CAPACITY_FACTOR=7.0 AUX_COEF=0.015 ROUTER_LEARNING_RATE=0.00001 \
  MODALITY_CYCLE=text,image,image,speech,speech \
  LEARNING_RATE=0.00045 LM_HEAD_LEARNING_RATE=0.00001 RETRIEVAL_HEAD_LEARNING_RATE=0.001 \
  CONTRASTIVE_COEF=0.15 IMAGE_CONTRASTIVE_COEF=0.4 SPEECH_CONTRASTIVE_COEF=0.6 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  IMAGE_CONDITIONAL_RANKING_COEF=1.5 SPEECH_CONDITIONAL_RANKING_COEF=2.0 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=19 CONDITIONAL_RANKING_NEGATIVE_MODE=random \
  CONDITIONAL_RANKING_TEMPERATURE=0.7

submit_e3 "sparse-moe-mm-frozenrouter-cap7-img15-${STAMP}" \
  FINAL_STEPS=5000 \
  TRAIN_ROUTER_GATES=0 \
  CAPACITY_FACTOR=7.0 AUX_COEF=0.015 \
  MODALITY_CYCLE=text,image,image,speech,speech \
  LEARNING_RATE=0.00045 LM_HEAD_LEARNING_RATE=0.00001 RETRIEVAL_HEAD_LEARNING_RATE=0.001 \
  CONTRASTIVE_COEF=0.15 IMAGE_CONTRASTIVE_COEF=0.4 SPEECH_CONTRASTIVE_COEF=0.6 \
  IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1 \
  IMAGE_CONDITIONAL_RANKING_COEF=1.5 SPEECH_CONDITIONAL_RANKING_COEF=2.0 \
  CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=19 CONDITIONAL_RANKING_NEGATIVE_MODE=random \
  CONDITIONAL_RANKING_TEMPERATURE=0.7

# Top-2 distillation candidates: text-only controls for potential E3 initialization later.
submit_distill "sparse-moe-top2-distill-hidden-cos-${STAMP}" \
  DISTILL_STEPS=1200 DISTILL_LOGIT_COEF=0.03 DISTILL_TEMPERATURE=3.0 \
  DISTILL_HIDDEN_COEF=0.05 DISTILL_HIDDEN_LAYERS=last DISTILL_HIDDEN_MODE=cosine \
  LEARNING_RATE=0.000008

submit_distill "sparse-moe-top2-distill-longce-${STAMP}" \
  DISTILL_STEPS=1600 DISTILL_LOGIT_COEF=0.02 DISTILL_TEMPERATURE=3.0 \
  LEARNING_RATE=0.000006 WEIGHT_DECAY=0.01

submit_distill "sparse-moe-top2-distill-gammatrain-${STAMP}" \
  TRAIN_GAMMA_SCALE=1 GAMMA_LEARNING_RATE=0.0003 \
  DISTILL_STEPS=1200 DISTILL_LOGIT_COEF=0.02 DISTILL_TEMPERATURE=3.0 \
  LEARNING_RATE=0.000008 WEIGHT_DECAY=0.0

# Held-out eval controls on the selected root with CI/per-query provenance.
CONTROL_RUN_ROOT="${CONTROL_RUN_ROOT:-outputs/sparse-moe-mm-rank49-fullbank-cap7-260709next}"
CONTROL_CHECKPOINT_PATH="${CONTROL_CHECKPOINT_PATH:-${CONTROL_RUN_ROOT}/E3_final_multimodal_top2/checkpoint_final.pt}"
STAMP="${STAMP}-evalctl" \
RUN_ROOT="$CONTROL_RUN_ROOT" \
CHECKPOINT_PATH="$CONTROL_CHECKPOINT_PATH" \
DATA_DIR="$DATA_DIR" \
BASE_OUT="${CONTROL_BASE_OUT:-outputs/eval-controls-heldout-${STAMP}}" \
EVALUATION_SCOPE=diagnostic EVAL_SPLIT_NAME="test_tail_offset125" QUERY_OFFSET=125 BOOTSTRAP_SAMPLES=2000 \
CONDITIONAL_QUERIES=125 \
bash scripts/submit_eval_control_sweep.sh
