#!/usr/bin/env bash
set -euo pipefail

# Research-quality E3 follow-up sweep after prefix-control evaluation.
# Each candidate is a single-GPU E3-only run; E4/E5/report are run only after selection.

STAMP="${STAMP:-260709rq-a}"
DATA_DIR="${DATA_DIR:-data/real_subset_clean_260708b}"
GPU="${GPU:-1}"
CPU="${CPU:-8}"
MEMORY="${MEMORY:-120G}"
COMMON_STEPS="${COMMON_STEPS:-5000}"

submit_candidate() {
  local name="$1"
  shift
  echo "Submitting ${name}"
  env     JOB_NAME="$name"     OUT="outputs/${name}"     DATA_DIR="$DATA_DIR"     GPU="$GPU" CPU="$CPU" MEMORY="$MEMORY"     FINAL_STEPS="$COMMON_STEPS"     ABLATION_STEPS=0 CAPACITY_ABLATION_STEPS=0 EXPERT_ABLATION_STEPS=0     POSTPROCESS_REQUIRED_RUNS=0     TEXT_EVAL_BLOCKS=160 RETRIEVAL_EVAL_SAMPLES=250 CONDITIONAL_EVAL_SAMPLES=250     IMAGE_EVAL_SAMPLES=250 SPEECH_EVAL_SAMPLES=250     TRAIN_BATCH_SIZE=4 EVAL_BATCH_SIZE=8     TRAIN_LM_HEAD=1 TRAIN_EXPERTS=0     IMAGE_PREFIX_TOKENS=50 AUDIO_PREFIX_TOKENS=64 ENCODER_FEATURE_TOKENS=100     REAL_MAX_SOURCE_AUDIO_SECONDS=6 REAL_MAX_TRANSCRIPT_WORDS=18     "$@"     bash scripts/submit_e3_candidate_runai.sh
}

# 1) Harder conditional ranking to address weak hard/50-way image matching.
submit_candidate "sparse-moe-rq-e3-rank49-cap7-${STAMP}"   CAPACITY_FACTOR=7.0 AUX_COEF=0.02   MODALITY_CYCLE=text,image,image,speech,speech   CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=49 CONDITIONAL_RANKING_TEMPERATURE=0.7   IMAGE_CONDITIONAL_RANKING_COEF=1.0 SPEECH_CONDITIONAL_RANKING_COEF=2.0   CONTRASTIVE_COEF=0.0 IMAGE_CONTRASTIVE_COEF=0.0 SPEECH_CONTRASTIVE_COEF=0.0   LEARNING_RATE=0.0006 LM_HEAD_LEARNING_RATE=0.00001 WEIGHT_DECAY=0.0 GRAD_CLIP=5.0

# 2) Higher capacity + stronger aux without router training, targeting prefix overflow.
submit_candidate "sparse-moe-rq-e3-cap8-aux02-${STAMP}"   CAPACITY_FACTOR=8.0 AUX_COEF=0.02   MODALITY_CYCLE=text,image,speech,speech,speech   CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=9 CONDITIONAL_RANKING_TEMPERATURE=0.7   IMAGE_CONDITIONAL_RANKING_COEF=0.5 SPEECH_CONDITIONAL_RANKING_COEF=3.0   CONTRASTIVE_COEF=0.0 IMAGE_CONTRASTIVE_COEF=0.0 SPEECH_CONTRASTIVE_COEF=0.0   LEARNING_RATE=0.0008 LM_HEAD_LEARNING_RATE=0.00001 WEIGHT_DECAY=0.0 GRAD_CLIP=5.0

# 3) Low-LR router gate tuning, testing whether routing balance improves without killing matching.
submit_candidate "sparse-moe-rq-e3-routerlow-cap7-${STAMP}"   CAPACITY_FACTOR=7.0 AUX_COEF=0.02 TRAIN_ROUTER_GATES=1 ROUTER_LEARNING_RATE=0.00001   MODALITY_CYCLE=text,image,speech,speech,speech   CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=9 CONDITIONAL_RANKING_TEMPERATURE=0.7   IMAGE_CONDITIONAL_RANKING_COEF=0.5 SPEECH_CONDITIONAL_RANKING_COEF=3.0   CONTRASTIVE_COEF=0.0 IMAGE_CONTRASTIVE_COEF=0.0 SPEECH_CONTRASTIVE_COEF=0.0   LEARNING_RATE=0.0008 LM_HEAD_LEARNING_RATE=0.00001 WEIGHT_DECAY=0.0 GRAD_CLIP=5.0

# 4) CE/contrastive-clean branch for qualitative generation and broad robustness.
submit_candidate "sparse-moe-rq-e3-clean-ce-${STAMP}"   FINAL_STEPS=6000 CAPACITY_FACTOR=7.0 AUX_COEF=0.02   MODALITY_CYCLE=text,image,speech   CONDITIONAL_NEGATIVES=9 CONDITIONAL_RANKING_NEGATIVES=9 CONDITIONAL_RANKING_TEMPERATURE=0.8   IMAGE_CONDITIONAL_RANKING_COEF=0.5 SPEECH_CONDITIONAL_RANKING_COEF=1.0   CONTRASTIVE_COEF=0.1 IMAGE_CONTRASTIVE_COEF=0.25 SPEECH_CONTRASTIVE_COEF=0.5   IMAGE_CONTRASTIVE_NEGATIVES=-1 SPEECH_CONTRASTIVE_NEGATIVES=-1   IMAGE_CENTER_POSITIVE_WEIGHT=1.0 SPEECH_CENTER_POSITIVE_WEIGHT=2.0   LEARNING_RATE=0.0004 LM_HEAD_LEARNING_RATE=0.00001 WEIGHT_DECAY=0.0 GRAD_CLIP=3.0
